### ISSUE TITLE
Popover's z-index with angular-material is wrong

### ISSUE THREAD

**Issue by briosheje** [pleerock/ng2-popover#59]
![schermata 2017-03-05 alle 00 05 46](https://cloud.githubusercontent.com/assets/1898880/23582963/888ace84-0137-11e7-92bd-1769a522078e.png)

Not sure why, but I can't really find any solution.

I'm printing the element in this way:

```
<label class="generals-list" *ngFor="let general of wave.generalsList" [popover]="generalPopover" [popoverOnHover]="true" popoverPlacement="right">
      <input type="radio" [(ngModel)]="wave.general" [value]="general">
      <img [src]="general.troupReference.iconImage" class="icon-micro" />
      <popover-content #generalPopover 
                  [title]="general.troupReference.name" 
                  placement="right"
                  [animation]="true">
                  <p [innerHTML]="general.troupReference.description"></p>
      </popover-content>
    </label>
```

Is this a known issue or am I just doing something terribly wrong? I have this issue in every other component really, regardless where I put the popover it always seems to stay behind the rest of the content.

I've tried fixing by attempting to force the z-index on the popover, image, input and label but none of them worked.

**Comment by PickleyD** [comment]
I'd have thought that setting `overflow: visible` on the skill tree panel should fix it. 

Is that an okay solution?

**Comment by briosheje** [comment]
Hello,

thanks for your reply.

I've tried setting overflow: visible on the parent element (the skill tree one), but the result is still the same:


![](http://image.prntscr.com/image/6b30d3b8ffb14144bff81c8c308082e4.png)

Not sure whether I should try forcing the z-index manually.

**Comment by PickleyD** [comment]
Hmm, what about the parent above that? The one for the whole left section

**Comment by briosheje** [comment]
I've tried to apply a class to the root component:
`.fix-overflow > * {
    overflow: visibile !important;
}`

but I'm still having the issue:

![image](https://cloud.githubusercontent.com/assets/1898880/23609346/d58620b2-026d-11e7-9235-b9fdfa52aab7.png)

The root component is rendering everything inside the view, not sure whether the .scss is applying to inner views aswell, but it should.

**Comment by PickleyD** [comment]
What about if you take the `>` out of that rule to make it apply to everything... just as an experiment.

Is this online anywhere so I can play with it?

**Comment by briosheje** [comment]
I've tried removing the > but I still have the same result. To experiment if it was applying to every element I've added a background-color: red; the result was quite confusing, it looks like that the rule is not being applied to the left component specifically (huh):

![image](https://cloud.githubusercontent.com/assets/1898880/23609601/1474f964-026f-11e7-85ab-9012a4b1163b.png)

So, since I thought it could probably have been the fact that the component is rendered dinamically, I've applied the ruleset to all the views and added the ruleset to each parent of each view. The result:

![image](https://cloud.githubusercontent.com/assets/1898880/23609693/83c3f4be-026f-11e7-97c1-c896d682a3f0.png)

Now I'm 100% sure the class is being applied, not sure why it is not working though :/

**Comment by PickleyD** [comment]
What happens if you move the popover html outside of the label, like this:

`<popover-content #generalPopover 
                  [title]="general.troupReference.name" 
                  placement="right"
                  [animation]="true">
                  <p [innerHTML]="general.troupReference.description"></p>
      </popover-content>

<label class="generals-list" *ngFor="let general of wave.generalsList" [popover]="generalPopover" [popoverOnHover]="true" popoverPlacement="right">
      <input type="radio" [(ngModel)]="wave.general" [value]="general">
      <img [src]="general.troupReference.iconImage" class="icon-micro" />     
    </label>`

?

**Comment by briosheje** [comment]
I can't take the popover-content outside of the label because each label has its own popover content:

![image](https://cloud.githubusercontent.com/assets/1898880/23611801/10dc8510-0279-11e7-89b6-a4eb33e6c5bb.png)

I've tried to wrap the whole thing in an unordered list by setting display inline-block, but the result is still the same:

![image](https://cloud.githubusercontent.com/assets/1898880/23611996/d213c202-0279-11e7-8d1a-0cde57009fa7.png)


Code:
![image](https://cloud.githubusercontent.com/assets/1898880/23612007/dffab74a-0279-11e7-9726-33d5d0616367.png)

(I've posted the picture to don't screw up the syntax)

It really seems the problem is related to something else, I could try to avoid using angular-material components, I'm not sure whether they could actually be the issue there (maybe the z-index of an md-card?)
